# Podfile for BeamShare iOS App
# Manages WebRTC dependency

platform :ios, '14.0'

target 'BeamShare' do
  use_frameworks!

  # WebRTC for iOS - Official Google implementation
  pod 'GoogleWebRTC', '~> 1.1'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
